DROP TABLE user_information IF EXISTS;

CREATE TABLE user_information (
  member_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email_id VARCHAR(100) NOT NULL,
  PRIMARY KEY(member_id)
);
